# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 677f67d6dd11ce7d0de9e1d3790f4b7afc24e550a43b5353f92365c0b0821b0fc4eec37503ea6caea62410ef1e976686dcc6a52049d7ec8efaa37a246d674617

test:
  secret_key_base: b9b03a8369a49c0d6e3910d0f181946ef6cd07652dca49bbadf688f41e3de9bb5428715e016165449210d72d8053559635d43a5280e67f05938b3687f569fa86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
